// Writes src/version.ts from package.json so `VERSION` is a plain constant (no readFileSync of ../package.json at
// import time, which bundlers cannot follow). Runs before tsc in `npm run build`; the generated file is committed
// and registry-manifests.test.ts asserts it matches.
import { readFileSync, writeFileSync } from "node:fs";
const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const out = new URL("../src/version.ts", import.meta.url);
const next = `// Generated by scripts/gen-version.mjs from package.json; do not edit.\nexport const VERSION = "${pkg.version}";\n`;
let cur = "";
try { cur = readFileSync(out, "utf8"); } catch { /* first run */ }
if (cur !== next) { writeFileSync(out, next); console.log(`src/version.ts → ${pkg.version}`); }
